# Generated by Django 5.0.6 on 2024-06-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='landmark',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
