# Generated by Django 5.0.6 on 2024-06-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_plotdetail_landmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotdetail',
            name='landmark',
        ),
    ]
