# Generated by Django 5.0.6 on 2024-06-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_remove_plotdetail_landmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='landmark',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
