# Generated by Django 5.0.6 on 2024-07-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_plotdetail_landmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaplingDetail',
        ),
        migrations.AlterField(
            model_name='plotdetail',
            name='dimension',
            field=models.CharField(choices=[('20x30', '20x30'), ('30x40', '30x40'), ('40x60', '40x60'), ('50x80', '50x80'), ('80x100', '80x100')], max_length=20),
        ),
    ]
