# Generated by Django 5.0.6 on 2024-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_delete_saplingdetail_alter_plotdetail_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='sapling',
            field=models.CharField(choices=[('oak', 'oak'), ('coconut', 'coconut'), ('olive', 'olive'), ('papaya', 'papaya'), ('neem', 'neem'), ('maple', 'maple')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
