# Generated by Django 5.0.6 on 2024-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0006_plotdetail_sapling'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdetail',
            name='num_of_sapling',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
