# Generated by Django 5.0.6 on 2024-07-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0007_plotdetail_num_of_sapling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotdetail',
            name='num_of_sapling',
            field=models.IntegerField(editable=False),
        ),
    ]
